### ISSUE TITLE
GSOC Proposal: Broken links

### ISSUE THREAD

**Issue by ghost** [klahnakoski/JSONQueryExpressionTests#1]
The links about snowflake schema are broken.

One under [The Solution](https://github.com/klahnakoski/JSONQueryExpressionTests/blob/master/docs/GSOC%20Proposal.md#the-solution) title and other [Schema-Independent Query Language?](https://github.com/klahnakoski/JSONQueryExpressionTests/blob/master/docs/GSOC%20Proposal.md#schema-independent-query-language)

They are trying to open this page:
https://en.wikipedia.org/wiki/Snowflake_schemahierarchical
I think you mean:
https://en.wikipedia.org/wiki/Snowflake_schema

**Comment by klahnakoski** [comment]
Yes, thank you.  I fixed it.
